### PR TITLE
Update readme.html

### PR DESCRIPTION
**Pull request by MrDoobPG**
Plexguide link change to the new one PGblitz.com

### CODE REVIEW

**Comment by Igglybuff** [comment]
Please can you update [readme.md](https://github.com/Igglybuff/awesome-piracy/blob/master/readme.md) as well?

Also, I usually just generate the HTML version with a plugin for Sublime Text.

**Comment by MrDoobPG** [comment]
Yes I can do it.

**Comment by karkouri990** [comment]
add website learninglcom.com

**Comment by MrDoobPG** [comment]
sorry... i was busy .. now its finish . Readme and this onw updatet 

thanks for share the links ;-)

**Pull request merged**
