### PR TITLE
Refracting Of Code And Deployement Of Website

### PR DESCRIPTION
**Pull request by tanaybhardwaj24**
## Changes

1. readme.html put under website-src/src by the name of index.html 
2. css of readme.html refactored to styles.css
3. deployed to vercel [link](https://official-awesome-piracy.vercel.app/)

## Final Changes 

1. Finished the website which is easy to update which uses strapdown js
2. Updated all the information

### CODE REVIEW

**Comment by Shakil-Shahadat** [comment]
Nice work. A couple of observations here,
- The link icons left to the headers are not working.
- The readme.html/index.html file is now obsolete and needs an update.
- Both index.html and styles.css files need a new line at the end.
- Won't Github pages be a better choice for a website?
- Manually updating the index.html file every once in a while will be cumbersome. Won't it be better to use libraries like [Showdown](https://github.com/showdownjs/showdown) to show the readme.md file on the fly?

**Comment by Shakil-Shahadat** [comment]
Excellent work.

**Comment by tanaybhardwaj24** [comment]
How much work do you think I must do before my pull request gets approved?

(this is my first timing doing a pull request in a major project)

**Comment by tanaybhardwaj24** [comment]
Ooh! Thanks.. by the index i meant index in the sense of how to website has a table of contents (which doesn't work and fixing it is nearly impossible) I have deleted the table of contents for now and thinking of how to integrate showdown in it!

**Comment by Shakil-Shahadat** [comment]
No, you don't need that index either. You just need to load readme.md file and showdown file inside index.html file and then invoke showdown on the readme.md so that it converts the file to html code on the client-side. The index.html file should be pretty straightforward.

**Comment by tanaybhardwaj24** [comment]
@Shakil-Shahadat I could not figure out how to use showdown so i used strapdown which basically does the same thing. Now the website is fully updated and very easy to update. You can check out the website and check if there are any bugs or errors

**Comment by Shakil-Shahadat** [comment]
Strapdown looks even better. But readme.md isn't loaded dynamically.

**Comment by tanaybhardwaj24** [comment]
> Strapdown looks even better. But readme.md isn't loaded dynamically.

Sorry I didn't understand...Can you elaborate? The website is a bit slow because it has to load 1500 lines of markdown on one go.

thanks for helping!

**Comment by tanaybhardwaj24** [comment]
@Igglybuff Both Alternate and Main websites are working. I will not be able to fix the navbar/index alone

**Comment by Shakil-Shahadat** [comment]
I believe I already did. You have removed things without explanation. There are many other problems too. This pr is now almost impossible to review now. If you want to change something from the readme.md, create new pr.

**Comment by tanaybhardwaj24** [comment]
What i have down -- 
1 -- Created the website whose source is all in website-src
2 -- I removed PIA as many others have also made a pull request for it to be removed.

and 

> Regarding approval, that depends on the maintainer. I am just a contributor like you.

at the end, it will be the authors choice to accept / deny the pull request

**Comment by Shakil-Shahadat** [comment]
For PIA, I already have a pr #503.

I have just tried to guide you, didn't want to see your work go to waste.

**Comment by tanaybhardwaj24** [comment]
Ooh! that is true, this pr is looking very untidy. I will wait if the author approves it or not. If they do not approve this i will create a pull request which is more tidy and with more information

**Comment by Igglybuff** [comment]
https://github.com/Igglybuff/awesome-piracy/pull/524#issuecomment-848969254

**Pull request closed without merging**
