### PR TITLE
Adds browser extensions to enable copy on sites

### PR DESCRIPTION
**Pull request by Shakil-Shahadat**

### CODE REVIEW

**Comment by Shakil-Shahadat** [comment]
I understand. I added it only because I removed 'anti-anti-copy'.

But if you want to be strictly piracy related then there are many other things out there that need to go.

I personally think, if it is useful then you should keep it, especially in the miscellaneous section. People will thank you rather than being mad.

**Comment by virtadpt** [comment]
Yes, please.

**Comment by Igglybuff** [comment]
A compromise might be to simply limit how many piracy-adjacent links are included in the list in each category. Will require some thought.

**Comment by Shakil-Shahadat** [comment]
I am here to help.

I suggest we go through each section and carefully check every link and decide what should stay and what shouldn't. I believe I have a lot to contribute. I'm currently going through issues but will soon start adding what I have.

If you are okay with this then we can make a plan. We can ask more people to contribute so that the work finishes faster.

**Pull request closed without merging**
