### PR TITLE
Android Apps Section

### PR DESCRIPTION
**Pull request by thehackingsage**
Download MOD APK

### CODE REVIEW

**Comment by Igglybuff** [comment]
Would this be better placed in the existing Android apps section?

**Comment by thehackingsage** [comment]
Fixed

**Comment by ibrahim1153** [comment]
Would this be a great set in the existing [Android apps](https://eagleapk.com/apps/) section?

**Comment by Igglybuff** [comment]
Could you rewrite the descriptions to be more grammatically digestible too please?

**Comment by musamaq** [comment]
You cal download Quality of mod Apk from [Nextgenapk](https://nextgenapk.com/). All mods are free of cost and virus protected.

**Comment by zinre** [comment]
Yes the [mod apk](https://randomapk.com ) is the best option to download free to favorite application

**Pull request closed without merging**
